# electrophstat/hardware/interfaces.py
from typing import Protocol, runtime_checkable, Tuple


@runtime_checkable
class PowerSupply(Protocol):
    """High-level contract for any DC bench supply (real or dummy)."""

    port: str | None      # e.g. 'COM6' or '/dev/ttyUSB0'

    # ---------- life-cycle ----------
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    @property
    def connected(self) -> bool: ...

    # ---------- control ----------
    def set_voltage(self, volts: float) -> None: ...
    def set_current(self, amps: float) -> None: ...
    def set_output(self, enable: bool) -> None: ...

    # ---------- monitoring ----------
    def read_output(self) -> Tuple[float, float]: ...
        # returns (voltage_V, current_A)


@runtime_checkable
class Pump(Protocol):
    """Contract for peristaltic / syringe pumps."""

    address: int  # Modbus or I2C, whatever

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    @property
    def connected(self) -> bool: ...

    def set_speed(self, rpm: float) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
